### ISSUE TITLE
Reorganize File Structure?

### ISSUE THREAD

**Issue by sarahzinger** [WomenWhoCodeNYC/Algorithms#57]
An idea open for discussion! Let me know what you think: what if we reorganized our file structure to be more like this:

```
-DateOfEvent.md (contains links to each challengeDescription)
-DifferentDateOfEvent.md 
-ChallengesRepo
    |---nameOfChallenge
            |---challengeDescription.md
            |---solutionsFolder
                  |---solutionInJavascript.js
                  |---solutionInRuby.rb
                  |---solutionInCPP.cpp
```

I feel like reorganizing in this way could ensure that people get a chance to revisit older problems more, and browse through all of our challenges easily. It can also save us from duplicating our code if we choose to reuse a problem or two some month.

**Comment by PaddyBadger** [comment]
sounds good to me!
